### ISSUE TITLE
GitHub Pages

### ISSUE THREAD

**Issue by patwater** [argo-marketplace/future_of_california#10]
May be worth hacking together a quick GitHub pages front end to make it easier for folks to sign up as supporters, get newsletter updates, share with their friends etc.? Curious to thoughts on the best way to do that with the current readme based approach for the principles. 1t1d

CC @vr00n @dmarulli

**Comment by patwater** [comment]
Something like this would be slick: https://civic-tech-timeline.github.io/

**Comment by patwater** [comment]
See: https://argo-marketplace.github.io/future_of_california/

**Comment by patwater** [comment]
- [ ] share on social media button
- [ ] [subscribe button ](https://github.com/mmistakes/minimal-mistakes/issues/1413)

**Comment by christophertull** [comment]
@patwater Looks like there is a bug with the signup form implementation that prevents any of the other embedded links from being clickable.

Looks like this is being caused by the `mc_embed_signup` div extending over the entire page and covering up the other links.

cc webmaster @dmarulli

**Comment by patwater** [comment]
Bleh thans for flagging @christophertull . I tweaked the html so the mailchimp form is outside (I think) the main page div class. The GitHub pages still looks the same though sometimes take a little while for changes to go through their servers. @dmarulli not urgent though when you get a sec would appreciate your insight as looking to leverage this page coming out of the Saturday workshop

Note also setup a bitly -- bit.ly/californias_future

**Comment by patwater** [comment]
Linking the conversation on the great PR fixing the email signup stuff for visibility: https://github.com/argo-marketplace/future_of_california/pull/15
