### ISSUE TITLE
Add a "How  to contribute" section.

### ISSUE THREAD

**Issue by vr00n** [argo-marketplace/future_of_california#4]
Consider adding a section in the README to guide non-tech folks to comment using Issues.
Maybe also [create a simple issue template](https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/)

**Comment by patwater** [comment]
There is this line in the ReadMe: "Contributing: This is a living document! Please feel free to submit a PR to improve the principles here. If you're not familiar with GitHub please feel free to email argo@argolabs.org with your suggested language."

Feel free to add language on Issues via a PR / add an issue template if you like.

**Comment by patwater** [comment]
@vr00n I added a [new issue template](https://github.com/argo-marketplace/future_of_california/commit/280b57a3c8ebc5f68f0b4ad481c64eb72144acc6) and made the how to contribute section more clear.
