### ISSUE TITLE
Name and location for the principles

### ISSUE THREAD

**Issue by patwater** [argo-marketplace/future_of_california#6]
There have been some good discussion about having a better name for these principles. (Open California evokes open data and also doesn't hint at technology). 

It may also be worthwhile to pick an iconic California location for a roundtable with key folks to hash out the final version of these principles. Big Sur? 

Name candidates:

- Public technology principles
- Open government principles
- Other ideas?

**Comment by vr00n** [comment]
+1 for public technology principles

**Comment by patwater** [comment]
Yeah I increasingly like it. I love the [Manifesto for Public Technology](https://civichall.org/civicist/manifesto-for-public-technology/). It also transcends the silly civic vs gov vs urban tech definition battles

**Comment by patwater** [comment]
Yes @vr00n the dirt simple *Public Technology Principles* was the clear favorite at the workshop this weekend. Bonus points as the implementation strategies are California specific though the principles apply far beyond the narrow geographic confines of this particular place. 1t1d
