### ISSUE TITLE
Digital Services

### ISSUE THREAD

**Issue by ramymik** [argo-marketplace/future_of_california#7]
How are the Principles incorporating the work of the CIO and Director of [Amy Tong](https://cdt.ca.gov/director/)  in leading the "Digital Services" or could we reframe the idea of the office leading a team in digital services?

**Comment by patwater** [comment]
@ramymik right now Implementation Strategy #2 calls for _"A new California Digital Service should be created to make modern design and information technology practices the new normal in California government. That effort should build from the UK Digital Service, US Digital Service, 18F and numerous other units at cities and countries around the globe."_

I've heard conflicting things btw about whether that Digital Service has already happened or is just rebranding existing positions. Anyway happy to refactor to better align with Jen's letter etc.

One thing I'd note though is that it is mission critical to also have people on the ground within government agencies working on the culture change issues. That's the motivation of @vr00n "Civic Tech Corps" idea which is sorta a CfA community fellowship scaled up for all of CA's state agencies and local governments. See Implementation Strategy 1 and Issue #2 https://github.com/argo-marketplace/future_of_california/issues/2

**Comment by patwater** [comment]
Updated the text based on our conversation with Jen to reflect that this is an office of CA Dept of Tech and not branded as a CA digital service. 1t1d
